# Generated by Django 5.1.2 on 2024-11-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_noticedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Elon',
        ),
        migrations.RenameModel(
            old_name='NoticeData',
            new_name='Elonlarim',
        ),
    ]
