# Generated by Django 5.1.2 on 2024-11-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_notice_elon_rename_noticedata_elonlarim'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elon',
            new_name='Notice',
        ),
    ]
